### **ЗАДАНИЕ НА ПОВТОРЕНИЕ МАТЕРИАЛА


In [1]:
import pandas as pd
import numpy as np

### Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [2]:
a = np.arange(12, 24)

a, type(a)

(array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]), numpy.ndarray)

### Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [3]:
a1 = np.reshape(a, (2, 6))
a2 = np.reshape(a, (3, 4))
a3 = np.reshape(a, (4, 3))
a4 = np.reshape(a, (6, 2))
a5 = np.reshape(a, (12, 1))

print(a1) 
print(a2) 
print(a3) 
print(a4) 
print(a5)

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


### Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк). Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

In [4]:
b1 = np.reshape(a, (2, -1))
b2 = np.reshape(a, (3, -1))
b3 = np.reshape(a, (4, -1))
b4 = np.reshape(a, (-1, 2))
b5 = np.reshape(a, (-1, 1))

print(b1) 
print(b2) 
print(b3) 
print(b4) 
print(b5)

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


### Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [5]:
b = np.random.randn(3,4).reshape(-1)

#b = b.flatten() - альтернативный вариант

b

array([ 0.55199051, -1.00367065, -1.06420524, -0.91311588, -0.82341489,
        1.26811737,  0.15337522,  1.47804067,  0.4432561 , -0.1075416 ,
        0.86183529,  0.80721572])

### Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [6]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

### Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [7]:
b = np.arange(20, 1, -2).reshape(-1, 1)

b

array([[20],
       [18],
       [16],
       [14],
       [12],
       [10],
       [ 8],
       [ 6],
       [ 4],
       [ 2]])

### Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [8]:
a = np.zeros((2,2), int)

b = np.zeros((3, 2), int)+1

v = np.vstack((a, b))

print(a)
print(b)
print(v)

[[0 0]
 [0 0]]
[[1 1]
 [1 1]
 [1 1]]
[[0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]]


### Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [9]:
a = np.arange(0, 12)

A = a.reshape(4, 3)

At = A.transpose()

B = A.dot(At)

from numpy import linalg as LA
#B_inv = LA.inv(B)

B, B.size

(array([[  5,  14,  23,  32],
        [ 14,  50,  86, 122],
        [ 23,  86, 149, 212],
        [ 32, 122, 212, 302]]), 16)

### Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [10]:
a = np.random.seed(42)

### Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно.

In [11]:
a = np.random.randint(0, 16, 16)
a

array([ 6,  3, 12, 14, 10,  7, 12,  4,  6,  9,  2,  6, 10, 10,  7,  4])

### Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [12]:
C = a.reshape(4, 4)

D = B + C*10

D_det = np.linalg.det(D)

D_rank = np.linalg.matrix_rank(D)

D_inv = LA.inv(D)

D_det, D_rank, D_inv

(-28511999.999999944,
 4,
 array([[ 0.00935396,  0.04486532,  0.05897517, -0.07286055],
        [-0.01503577, -0.00122896, -0.00192971,  0.00967873],
        [-0.00356692, -0.01782828, -0.04152146,  0.04326178],
        [ 0.00909091, -0.00181818,  0.01272727, -0.01090909]]))

### Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [13]:
D_inv = np.where(D_inv > 0, 1, 0)
print(D_inv)

E = np.where(D_inv == 1, B, C)
print(B)
print(C)
print(E)

[[1 1 1 0]
 [0 0 0 1]
 [0 0 0 1]
 [1 0 1 0]]
[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
[[ 6  3 12 14]
 [10  7 12  4]
 [ 6  9  2  6]
 [10 10  7  4]]
[[  5  14  23  14]
 [ 10   7  12 122]
 [  6   9   2 212]
 [ 32  10 212   4]]
